Translated to Brazilian Portuguese
MrOkiDoki/BattleBit-Community-Server-API pull request #104
Opened 2024-02-03 03:13 UTC by daguerpedro

Created a 100% Portuguese readme and linked it to the main readme.

2024-05-16 12:50 UTC, Julgers requested changes
Thanks for taking the time to translate this, looks great. I have one little request before merging it in however.

2024-05-16 12:50 UTC, Julgers commented on README.md
> +Language English | [中文](/README-zhCN.md) | [한국어](/README-koKR.md) | [Español](/README-esES.md) | [Português](/README-ptBR.md)
Could you perhaps add this to the other language READMEs as well? You added it to the English one only.

2024-05-22 19:40 UTC, daguerpedro commented on README.md
> +Language English | [中文](/README-zhCN.md) | [한국어](/README-koKR.md) | [Español](/README-esES.md) | [Português](/README-ptBR.md)
Done

2024-05-22 20:00 UTC, Julgers commented on README.md
> +Language English | [中文](/README-zhCN.md) | [한국어](/README-koKR.md) | [Español](/README-esES.md) | [Português](/README-ptBR.md)
Thanks!

2024-05-22 20:01 UTC, Julgers approved these changes
Approved.

2024-05-22 20:01 UTC, merged